name: Deploy
# on: push
# branches:
#   - master
on:
  pull_request:
    branches:
      - feature/*
jobs:
  deploy:
    name: Deploy to firebase
    steps:
      - name: Install dependencies
        with:
          node-version: 16
        run: |
          npm i firebase-tools --global &&
          npm i
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        run: npm run deploy --token "$FIREBASE_TOKEN"
