name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test
        run: cd daka && ls -al && echo $(git rev-parse --short=7 HEAD)
      - name: Install dependencies
        run: npm i firebase-tools --location=global && npm i
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run deploy --token "$FIREBASE_TOKEN"
